version: "3.9"

services:
  db:
    ports:
      - "5432:5432"
    image: mdillon/postgis:10
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Website:/Website
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db