# Generated by Django 3.2.12 on 2022-02-28 16:02
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]
    operations = [
        CreateExtension('postgis'),
    ]
