# Generated by Django 3.2.12 on 2022-03-02 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220301_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='created_add',
        ),
        migrations.AddField(
            model_name='postitem',
            name='created_app',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.postitem'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.postitem'),
        ),
    ]
