# Generated by Django 3.2.12 on 2022-03-02 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220302_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='postitem',
            name='created_app',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='postitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.postcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postitem',
            name='time_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='item',
        ),
        migrations.AddField(
            model_name='posttag',
            name='item',
            field=models.ManyToManyField(to='app.PostItem'),
        ),
    ]
